# Site settings
title: THEFIRSTFLOOR 3DXR Developer
email: hello@thefirstfloor.nl
description: Freelance developer of interactive media> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: jeroenduhmooij
github_username: thefirstfloor
bluesky_username: thefirstfloor

# Build settings
markdown: kramdown
